### ISSUE TITLE
error TS2498: Module '"mitt"' uses 'export =' and cannot be used with 'export *'

### ISSUE THREAD

**Issue by wangzhiwei1888** [cong-min/mp-gulpfile#1]
执行 npm run start 报错

src/utils/index.ts(2,23): error TS2498: Module '"mitt"' uses 'export =' and cannot be used with 'export *'.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
[17:32:34] 'ts' errored after 1.44 s
[17:32:34] Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/wangzhiwei8/WeChatProjects/my-project/node_modules/_gulp-typescript@6.0.0-alpha.1@gulp-typescript/release/output.js:131:43)
    at applySourceMap.then.appliedSourceMap (/Users/wangzhiwei8/WeChatProjects/my-project/node_modules/_gulp-typescript@6.0.0-alpha.1@gulp-typescript/release/output.js:44:22)
    at <anonymous>
[17:32:34] 'default' errored after 1.46 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangzhiwei8/.npm/_logs/2020-08-11T09_32_34_644Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangzhiwei8/.npm/_logs/2020-08-11T09_32_34_675Z-debug.log
jason-jritdeMacBook-Pro:my-project wangzhiwei8$

**Comment by cong-min** [comment]
已修复：https://github.com/mcc108/mp-gulpfile/commit/78acde430abfcbb388b2385699c972e882dafb9b#diff-78be3e8669f97184968e1fc6b0aa36d4
